using Application.MainModule.Administration.FileManagement.DTO;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/09/04 - 11:36:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Application.MainModule.Administration.CompanyManagement.DTO
{
    [DataContract()]
    public partial class DTOCompany
    {
        [DataMember()]
        public Int32 IdCompany { get; set; }

        [DataMember()]
        [Required]
        [Display(Name = "Nombre de Compañía")]
        public String Name { get; set; }

        [Required]
        [Display(Name = "CUIT")]
        public String CUIT { get; set; }

        [Required]
        [Display(Name = "Address")]
        public String Address { get; set; }

        [Required]
        [Display(Name = "Número")]
        public string Number { get; set; }

        [Required]
        [Display(Name = "Provincia")]
        public String State { get; set; }

        [Required]
        [Display(Name = "País")]
        public string Country { get; set; }

        public DTOFile File { get; set; }

        [DataMember()]
        public Int32 IdFile { get; set; }

        public DTOCompany()
        {
        }

        public DTOCompany(Int32 idCompany, String name, String cuit, String address, String number, String state, String country, DTOFile file)
        {
            this.IdCompany = idCompany;
			this.Name = name;
			this.CUIT = cuit;
			this.Address = address;
            this.Number = number;
            this.State = state;
            this.Country = country;
            this.File = file;

            if (file != null)
                IdFile = file.IdFile;
            else
                IdFile = 0;
        }
    }
}
