//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/07/04 - 10:51:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Application.MainModule.Administration.RolesManagement
{
    [DataContract()]
    public partial class DTOMenu
    {
        [DataMember()]
        public Int32 IDMenu { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Area { get; set; }

        [DataMember()]
        public String Controller { get; set; }

        [DataMember()]
        public String Action { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Nullable<Int32> IDParent { get; set; }

        [DataMember()]
        public Nullable<Int32> IDMenuModule { get; set; }

        [DataMember()]
        public List<DTOMenu> webpages_Menu1 { get; set; }

        [DataMember()]
        public DTOMenu webpages_Menu2 { get; set; }

        public DTOMenu()
        {
        }

        public DTOMenu(Int32 iDMenu, String name, String area, String controller, String action, String description, Nullable<Int32> iDParent, Nullable<Int32> iDMenuModule, List<DTOMenu> webpages_Menu1, DTOMenu webpages_Menu2)
        {
            this.IDMenu = iDMenu;
            this.Name = name;
            this.Area = area;
            this.Controller = controller;
            this.Action = action;
            this.Description = description;
            this.IDParent = iDParent;
            this.IDMenuModule = iDMenuModule;
            this.webpages_Menu1 = webpages_Menu1;
            this.webpages_Menu2 = webpages_Menu2;
        }
    }
}
