using Application.MainModule.Administration.Culture.DTO;
using Application.MainModule.Administration.FileManagement.DTO;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/09/04 - 11:36:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Application.MainModule.Administration.RolesManagement.DTO
{
    [DataContract()]
    public partial class DTOUserForEdit
    {
        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        [Required]
        [Display(Name = "Nombre de Usuario")]
        public String UserName { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public String FirstName { get; set; }

        [Required]
        [Display(Name = "Apellido")]
        public String LastName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Correo Electronico")]
        public string Email { get; set; }


        [Display(Name = "Idioma")]
        public int IdCulture { get; set; }

        [Display(Name = "Idioma")]

        public DTOFile File { get; set; }

        [DataMember()]
        public Int32 FileId { get; set; }

        public DTOUserForEdit()
        {
        }

        public DTOUserForEdit(Int32 userId, String userName, String firstName, String lastName, String Email,DTOFile file)
        {
			this.UserId = userId;
			this.UserName = userName;
			this.FirstName = firstName;
			this.LastName = lastName;
            this.Email = Email;
            this.File = file;
            if (file != null)
                FileId = file.IdFile;
        }
    }
}
