//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/09/03 - 16:01:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Application.MainModule.Administration.RolesManagement.DTO
{
    [DataContract()]
    public partial class DTOUserForRoles
    {
        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public String UserName { get; set; }

        public ICollection<DTORoleForUsers> roles { get; set; }

        public DTOUserForRoles()
        {
        }

        public DTOUserForRoles(Int32 userId, String userName)
        {
			this.UserId = userId;
			this.UserName = userName;
        }
    }
}
