using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using Domain.Entities;
using Infrastructure.Data.Core;
using System.Data.Entity.SqlServer;
using System.Data.Entity.Infrastructure.Interception;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    public partial class MobyDickEntities : DbContext
    {
        public MobyDickEntities()
            : base("name=MobyDickEntities")
        {
    		var ensureDLLIsCopied = SqlProviderServices.Instance;
    		//DbInterception.Add(new SoftDeleteCommandInterceptor()); 
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Membership> webpages_Membership { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Behavior> webpages_Behavior { get; set; }
        public virtual DbSet<File> webpages_File { get; set; }
        public virtual DbSet<Menu> webpages_Menu { get; set; }
        public virtual DbSet<MenuModule> webpages_MenuModule { get; set; }
        public virtual DbSet<RoleInBehavior> webpages_RoleInBehavior { get; set; }
        public virtual DbSet<Roles> webpages_Roles { get; set; }
        public virtual DbSet<Company> webpages_Company { get; set; }
        public virtual DbSet<Culture> webpages_Culture { get; set; }
        public virtual DbSet<Resources> webpages_Resources { get; set; }
        public virtual DbSet<Checkpoint> webpages_Checkpoint { get; set; }
    }
}
