//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/09/03 - 15:47:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Application.MainModule.Administration.RolesManagement.DTO;
using Infrastructure.Data;
using System.Data.Objects.DataClasses;
using Domain.Entities;

namespace Application.MainModule.Administration.RolesManagement.DTOAdapters
{

    /// <summary>
    /// Assembler for <see cref="Roles"/> and <see cref="RolesDTO"/>.
    /// </summary>
    public static partial class AdapterRoleForUsers
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="RolesDTO"/> converted from <see cref="Roles"/>.</param>
        static partial void OnDTO(this Roles entity, DTORoleForUsers dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Roles"/> converted from <see cref="RolesDTO"/>.</param>
        static partial void OnEntity(this DTORoleForUsers dto, Roles entity);

        /// <summary>
        /// Converts this instance of <see cref="RolesDTO"/> to an instance of <see cref="Roles"/>.
        /// </summary>
        /// <param name="dto"><see cref="RolesDTO"/> to convert.</param>
        public static Roles ToEntityRoleForUsers(this DTORoleForUsers dto)
        {
            if (dto == null) return null;

            var entity = new Roles();

            entity.RoleId = dto.RoleId;
            entity.RoleName = dto.RoleName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Roles"/> to an instance of <see cref="RolesDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Roles"/> to convert.</param>
        public static DTORoleForUsers ToDTORoleForUsers(this Roles entity)
        {
            if (entity == null) return null;

            var dto = new DTORoleForUsers();

            dto.RoleId = entity.RoleId;
            dto.RoleName = entity.RoleName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="RolesDTO"/> to an instance of <see cref="Roles"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Roles> ToEntitiesRoleForUsers(this IEnumerable<DTORoleForUsers> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntityRoleForUsers()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Roles"/> to an instance of <see cref="RolesDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DTORoleForUsers> ToDTOsRoleForUsers(this IEnumerable<Roles> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTORoleForUsers()).ToList();
        }
    }
}
