//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/09/03 - 11:58:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Infrastructure.Data;
using Domain.Entities;
using Application.MainModule.Services;

namespace Application.MainModule.Administration.RolesManagement
{

    /// <summary>
    /// Assembler for <see cref="Users"/> and <see cref="DTOUser"/>.
    /// </summary>
    public static partial class AdapterUserForExportList
    {
        /// <summary>
        /// Converts this instance of <see cref="Users"/> to an instance of <see cref="DTOUser"/>.
        /// </summary>
        /// <param name="entity"><see cref="Users"/> to convert.</param>
        public static object ToDTOForExportList(this Users entity)
        {
            if (entity == null) return null;

            var dto = new DTOUserForExportList();

            dto.UserName = entity.UserName;
            dto.CompleteName = string.Concat(entity.FirstName, " ", entity.LastName);
            dto.Email = entity.Email;

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="Users"/> to an instance of <see cref="DTOUser"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<object> ToDTOsForExportList(this IEnumerable<Users> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTOForExportList()).ToList();
        }

    }
}
