//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/09/03 - 11:58:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Infrastructure.Data;
using Domain.Entities;
using Application.MainModule.Services;
using Application.MainModule.Administration.RolesManagement;

namespace Application.MainModule.Administration.Resource
{

    /// <summary>
    /// Assembler for <see cref="Company"/> and <see cref="DTOCompany"/>.
    /// </summary>
    public static partial class AdapterResource
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DTOCompany"/> converted from <see cref="Company"/>.</param>
        static partial void OnDTO(this Resources entity, DTOResource dto);

        /// <summary>
        /// Converts this instance of <see cref="Company"/> to an instance of <see cref="DTOCompany"/>.
        /// </summary>
        /// <param name="entity"><see cref="Company"/> to convert.</param>
        public static DTOResource ToDTO(this Resources entity)
        {
            if (entity == null) return null;

            var dto = new DTOResource();

            dto.Name = entity.Name;
            dto.Culture = entity.Culture.Code;
            dto.Value = entity.Value;
            if (entity.IDMenu.HasValue)
                dto.IdMenu = entity.IDMenu.Value;
            dto.Menu = AdapterMenu.ToDTOMenu(entity.Menu);

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="Users"/> to an instance of <see cref="DTOUser"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DTOResource> ToDTOs(this IEnumerable<Domain.Entities.Resources> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
    }
}
