using Application.MainModule.Administration.FileManagement.DTO;
using Application.MainModule.Administration.RolesManagement;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/09/04 - 11:36:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Application.MainModule.Administration
{
    [DataContract()]
    public partial class DTOResource
    {
        public string Name { get; set; }
        public string Value { get; set; }
        public string Culture { get; set; }
        public int IdMenu { get; set; }
        public DTOMenu Menu { get; set; }

        public DTOResource()
        {
        }

        public DTOResource(String name, String value, String culture, int IdMenu)
        {
            this.Name = name;
            this.Value = value;
            this.Culture = culture;
            this.IdMenu = IdMenu;
        }
    }
}