//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkpoint
    {
        public int IdCheckpoint { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string IpService { get; set; }
        public bool deleted { get; set; }
        public int op { get; set; }
        public System.DateTime stamp { get; set; }
    }
}
