//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int IdCompany { get; set; }
        public string Name { get; set; }
        public string CUIT { get; set; }
        public string Address { get; set; }
        public string Number { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> Logo { get; set; }
        public int op { get; set; }
        public System.DateTime stamp { get; set; }
    
        public virtual File webpages_File { get; set; }
    }
}
