//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culture
    {
        public Culture()
        {
            this.Users = new HashSet<Users>();
            this.Resources = new HashSet<Resources>();
        }
    
        public int IdCulture { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Resources> Resources { get; set; }
    }
}
