//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.Users = new HashSet<Users>();
            this.webpages_Company = new HashSet<Company>();
        }
    
        public int IdFile { get; set; }
        public byte[] FileData { get; set; }
        public string MimeType { get; set; }
        public System.DateTime Date { get; set; }
        public string FileName { get; set; }
        public int op { get; set; }
        public System.DateTime stamp { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Company> webpages_Company { get; set; }
    }
}
