//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.SubMenues = new HashSet<Menu>();
            this.Behavior = new HashSet<Behavior>();
            this.Roles = new HashSet<Roles>();
            this.webpages_Resources = new HashSet<Resources>();
        }
    
        public int IDMenu { get; set; }
        public Nullable<int> IDMenuModule { get; set; }
        public Nullable<int> IDParent { get; set; }
        public string Name { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public int Orden { get; set; }
        public int Axis_X { get; set; }
        public int Axis_Y { get; set; }
        public int op { get; set; }
        public System.DateTime stamp { get; set; }
    
        public virtual ICollection<Menu> SubMenues { get; set; }
        public virtual Menu ParentMenu { get; set; }
        public virtual MenuModule MenuModule { get; set; }
        public virtual ICollection<Behavior> Behavior { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
        public virtual ICollection<Resources> webpages_Resources { get; set; }
    }
}
