//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuModule
    {
        public MenuModule()
        {
            this.Menu = new HashSet<Menu>();
        }
    
        public int IDMenuModule { get; set; }
        public string Description { get; set; }
        public int op { get; set; }
        public System.DateTime stamp { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
    }
}
