//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> IDMenu { get; set; }
        public int IdResource { get; set; }
        public int IdCulture { get; set; }
        public int op { get; set; }
        public System.DateTime stamp { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Culture Culture { get; set; }
    }
}
