//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleInBehavior
    {
        public int IDRoleInBehavior { get; set; }
        public int IDRole { get; set; }
        public int IDBehavior { get; set; }
        public bool Authorization { get; set; }
    
        public virtual Behavior Behavior { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
