//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Roles = new HashSet<Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdFile { get; set; }
        public int op { get; set; }
        public System.DateTime stamp { get; set; }
        public bool deleted { get; set; }
        public int IdCulture { get; set; }
    
        public virtual File File { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
        public virtual Membership webpages_Membership { get; set; }
        public virtual Culture webpages_Culture { get; set; }
    }
}
